version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: career-os-postgres
    environment:
      POSTGRES_DB: career_os
      POSTGRES_USER: career_os_user
      POSTGRES_PASSWORD: career_os_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup-database.sql:/docker-entrypoint-initdb.d/setup-database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U career_os_user -d career_os"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: career-os-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: career-os-network
